In [75]:
import pandas as pd
import numpy as np
data = {'car' : [np.nan,"Volvo", "Ford"], 'new car': ["Volvo", "Mustang", "Honda"]}



clean  = pd.Series(data)
print(clean)
ordered = pd.DataFrame(data,index = [1, 2, 3])
#ordered=ordered.fillna("BMW")
print(ordered)

ordered.isna()

car             [nan, Volvo, Ford]
new car    [Volvo, Mustang, Honda]
dtype: object
     car  new car
1    NaN    Volvo
2  Volvo  Mustang
3   Ford    Honda


car  new car
1   True    False
2  False    False
3  False    False

In [87]:
a = np.array([(1, 2, 3), (3, 2, 4)])
h = a.reshape(3,2)
print(h)

[[1 2]
 [3 3]
 [2 4]]


In [131]:
print(h[0:2, 1])

[2 3]


In [133]:
h.sum(axis=0)

array([6, 9])

In [137]:
print(a+a)

[[2 4 6]
 [6 4 8]]


In [67]:
ordered[['car', 'new car']]

car  new car
1    BMW    Volvo
2  Volvo  Mustang
3   Ford    Honda

In [63]:
ordered.loc[[1, 2, 3]]

car  new car
1    BMW    Volvo
2  Volvo  Mustang
3   Ford    Honda