In [15]:
import numpy as np
scores = np.array([(20, 30, 35, 28), (40, 30, 29, 35), (34, 35, 19, 36), (30, 30, 30, 39)])
# print(scores)

sum = scores.sum(axis = 1)
print(f"per student sum = {sum}")

average = 

per student sum = [113 134 124 129]


In [41]:
a = "youraj ali"
help(a.split)

Help on built-in function split:

split(sep=None, maxsplit=-1) method of builtins.str instance
    Return a list of the substrings in the string, using sep as the separator string.

      sep
        The separator used to split the string.

        When set to None (the default value), will split on any whitespace
        character (including \n \r \t \f and spaces) and will discard
        empty strings from the result.
      maxsplit
        Maximum number of splits.
        -1 (the default value) means no limit.

    Splitting starts at the front of the string and works to the end.

    Note, str.split() is mainly useful for data that has been intentionally
    delimited.  With natural text that includes punctuation, consider using
    the regular expression module.



In [113]:
val = input("Enter array elements with space: ").split()
val2 = input("Enter second array elements with space: ").split()
val3 = input("Enter third array element with space: ").split()

testarr = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

stored = np.array(val, dtype=int)
stored2 = np.array(val2, dtype=int)
stored3 = np.array(val3, dtype = int)

stored4 = np.stack((stored, stored2, stored3))

print(f"A + B = {stored4 + testarr}")
print(f"A - B = {stored4 - testarr}")
print(f"A * B = {np.matmul(testarr, stored4)}")

Enter array elements with space:  1 1 1
Enter second array elements with space:  2 2 2
Enter third array element with space:  3 3 3


A + B = [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
A - B = [[ 0 -1 -2]
 [-2 -3 -4]
 [-4 -5 -6]]
A * B = [[14 14 14]
 [32 32 32]
 [50 50 50]]


In [127]:
import pandas as pd

data = {
    'Name': ['Ali', 'Sara', 'John', 'Fatima', 'Zara', 'Ahmad', 'Umar', 'Asma'],
    'Age': [20, 22, 21, 23, 22, 20, 24, 21],
    'Score': [85, 90, 72, 60, 88, 92, 78, 67]
}
df = pd.DataFrame(data)
df.set_index('Name', inplace=True)

# Filter
filtered = df[df['Score'] >= 75]
print("Filtered (Score >= 75):\n", filtered)

# Sort by Age descending
sorted_df = df.sort_values('Age', ascending=True)
print("Sorted by Age:\n", sorted_df)


Filtered (Score >= 75):
        Age  Score
Name             
Ali     20     85
Sara    22     90
Zara    22     88
Ahmad   20     92
Umar    24     78
Sorted by Age:
         Age  Score
Name              
Ali      20     85
Ahmad    20     92
John     21     72
Asma     21     67
Sara     22     90
Zara     22     88
Fatima   23     60
Umar     24     78


In [141]:
help(np.matmul)

Help on ufunc:

matmul = <ufunc 'matmul'>
    matmul(x1, x2, /, out=None, *, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj, axes, axis])

    Matrix product of two arrays.

    Parameters
    ----------
    x1, x2 : array_like
        Input arrays, scalars not allowed.
    out : ndarray, optional
        A location into which the result is stored. If provided, it must have
        a shape that matches the signature `(n,k),(k,m)->(n,m)`. If not
        provided or None, a freshly-allocated array is returned.
    **kwargs
        For other keyword-only arguments, see the
        :ref:`ufunc docs <ufuncs.kwargs>`.

        .. versionadded:: 1.16
           Now handles ufunc kwargs

    Returns
    -------
    y : ndarray
        The matrix product of the inputs.
        This is a scalar only when both x1, x2 are 1-d vectors.

    Raises
    ------
    ValueError
        If the last dimension of `x1` is not the same size as
        the second-to-last dimension 

In [147]:
from bs4 import BeautifulSoup as BS
import urllib.request

help(BS.get)

Help on function get in module bs4.element:

get(self, key, default=None)
    Returns the value of the 'key' attribute for the tag, or
    the value given for 'default' if it doesn't have that
    attribute.

